"""
File Name: explanation_consistency.py
Module: Explainability - Consistency Evaluation
Description:
    Provides utilities for measuring consistency between different explanation
    methods in the TruthLens AI system. This module computes correlation
    statistics between token importance scores generated by different
    explainability algorithms such as SHAP, Integrated Gradients, Attention,
    and LIME.

    These metrics are commonly used in interpretability research to evaluate
    whether explanation methods agree with each other.

Dependencies:
    logging
    typing
    numpy

Inputs:
    shap_importance
    integrated_gradients
    attention_scores
    lime_importance

Outputs:
    Dictionary of pairwise consistency metrics
"""

from __future__ import annotations

import logging
from typing import Dict, List, Optional

import numpy as np

logger = logging.getLogger(__name__)


class ExplanationConsistency:
    """
    Computes consistency metrics between explanation methods.
    """

    def __init__(self) -> None:
        logger.info("ExplanationConsistency initialized")

    @staticmethod
    def _extract_scores(
        items: Optional[List[Dict]],
        key: str,
    ) -> Optional[np.ndarray]:
        """
        Extract score vector from explanation items.
        """
        if not items:
            return None

        try:
            scores = [float(item.get(key, 0.0)) for item in items]
            return np.asarray(scores, dtype=float)
        except Exception as exc:  # pragma: no cover
            logger.warning("Failed to extract scores: %s", exc)
            return None

    @staticmethod
    def _extract_lime_scores(
        items: Optional[List],
    ) -> Optional[np.ndarray]:
        """
        Extract scores from LIME explanation format.
        """
        if not items:
            return None

        try:
            scores = [float(score) for _, score in items]
            return np.asarray(scores, dtype=float)
        except Exception as exc:  # pragma: no cover
            logger.warning("Failed to extract LIME scores: %s", exc)
            return None

    @staticmethod
    def _align_lengths(a: np.ndarray, b: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        """
        Align vectors to minimum common length.
        """
        length = min(len(a), len(b))
        return a[:length], b[:length]

    @staticmethod
    def _correlation(a: np.ndarray, b: np.ndarray) -> float:
        """
        Compute Pearson correlation safely.
        """
        if a.size == 0 or b.size == 0:
            return 0.0

        a, b = ExplanationConsistency._align_lengths(a, b)

        if a.size < 2:
            return 0.0

        corr = np.corrcoef(a, b)[0, 1]

        if np.isnan(corr):
            return 0.0

        return float(corr)

    def compute(
        self,
        shap_importance: Optional[List[Dict]] = None,
        integrated_gradients: Optional[List[Dict]] = None,
        attention_scores: Optional[List[Dict]] = None,
        lime_importance: Optional[List] = None,
    ) -> Dict[str, float]:
        """
        Compute pairwise explanation consistency metrics.
        """

        shap_scores = self._extract_scores(shap_importance, "importance")
        ig_scores = self._extract_scores(integrated_gradients, "importance")
        attention_scores_vec = self._extract_scores(attention_scores, "attention")
        lime_scores = self._extract_lime_scores(lime_importance)

        results: Dict[str, float] = {}

        if shap_scores is not None and ig_scores is not None:
            results["shap_vs_ig"] = self._correlation(shap_scores, ig_scores)

        if shap_scores is not None and attention_scores_vec is not None:
            results["shap_vs_attention"] = self._correlation(
                shap_scores,
                attention_scores_vec,
            )

        if ig_scores is not None and lime_scores is not None:
            results["ig_vs_lime"] = self._correlation(
                ig_scores,
                lime_scores,
            )

        if shap_scores is not None and lime_scores is not None:
            results["shap_vs_lime"] = self._correlation(
                shap_scores,
                lime_scores,
            )

        if ig_scores is not None and attention_scores_vec is not None:
            results["ig_vs_attention"] = self._correlation(
                ig_scores,
                attention_scores_vec,
            )

        logger.info("Explanation consistency computed")

        return results